version: '3'

services:
    web_app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: {{cookiecutter.repo_name}}_app
        image: {{cookiecutter.docker_registry}}/{{cookiecutter.repo_name}}_app
        restart: always
        ports:
          - "8501:8501"
